#!/usr/bin/env python3
"""Collect original notices for declared and imported Go modules; run at repo root."""
import hashlib
import json
import pathlib
import re
import shutil
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "licenses" / "go"

def go(*args):
    return subprocess.check_output(["go", *args], cwd=ROOT, text=True)

def objects(text):
    decoder = json.JSONDecoder()
    while text.strip():
        value, end = decoder.raw_decode(text.lstrip())
        yield value
        text = text.lstrip()[end:]

subprocess.run(["go", "mod", "download"], cwd=ROOT, check=True)
modules = {m["Path"]: m for m in objects(go("list", "-m", "-json", "all")) if not m.get("Main")}
declared = {m["Path"] for m in json.loads(go("mod", "edit", "-json"))["Require"]}
used = set(go("list", "-deps", "-test", "-f", "{{if .Module}}{{.Module.Path}}{{end}}", "./...").splitlines()) & modules.keys()
manifest = []
for name in sorted(declared | used):
    module = modules[name]
    source = pathlib.Path(module["Dir"])
    target = OUT / (name + "@" + module["Version"])
    notices = []
    for path in sorted(source.rglob("*")):
        if not path.is_file() or path.suffix in {".go", ".s", ".c", ".h", ".py", ".sh"} or not re.match(r"(?i)^(licen[cs]e|copying|notice|patents|authors|copyright)([._-]|$)", path.name):
            continue
        rel = path.relative_to(source)
        dest = target / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(path, dest)
        notices.append({"file": str(dest.relative_to(ROOT)), "sha256": hashlib.sha256(dest.read_bytes()).hexdigest()})
    if not notices:
        raise SystemExit("Missing notices: " + name)
    manifest.append({"module": name, "version": module["Version"], "sum": module.get("Sum", ""),
                     "scope": "application or tests" if name in used else "declared; not imported on this platform", "notices": notices})
OUT.mkdir(parents=True, exist_ok=True)
(OUT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
(OUT / "module-graph.json").write_text(json.dumps([{k: m[k] for k in ("Path", "Version", "Sum") if k in m} for m in modules.values()], indent=2) + "\n")
lines = ["# Go dependency notices", "", "Generated by `python3 scripts/licenses.py` on the current build platform.", "",
         "Includes every module declared in go.mod and every module imported by application packages or tests.",
         "The complete selected module graph is in [module-graph.json](module-graph.json); many graph entries are upstream tools or unused packages, not code distributed by this project.",
         "Original texts and checksums are recorded in [manifest.json](manifest.json). Keep all notices when redistributing binaries.", "",
         "| Module | Version | Scope | Original notices |", "| --- | --- | --- | --- |"]
for item in manifest:
    links = ["[" + pathlib.Path(n["file"]).name + "](" + n["file"].removeprefix("licenses/go/") + ")" for n in item["notices"]]
    lines.append("| `" + item["module"] + "` | `" + item["version"] + "` | " + item["scope"] + " | " + ", ".join(links) + " |")
(OUT / "README.md").write_text("\n".join(lines) + "\n")
print(f"Collected notices for {len(manifest)} modules ({len(used)} imported by application or tests).")
print("Review changed licenses, remove obsolete version directories, and rerun go-licenses after dependency updates.")
